
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustNonConf(object):

    def ShowEntCustMessageBox(self,title,message):
        msgBox=QtWidgets.QMessageBox()
        msgBox.setWindowTitle(title)
        msgBox.setIcon(QtWidgets.QMessageBox.Information)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def ShowEntCustWMessageBox(self,title,message):
        msgBox=QtWidgets.QMessageBox()
        msgBox.setWindowTitle(title)
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def CustNonConfCal(self):

        SrNo=int(self.lineEdit.text())
        Date=str(self.lineEdit_2.text())
        CustomerNo=str(self.lineEdit_3.text())
        PartName=str(self.lineEdit_4.text())
        PartNo=str(self.lineEdit_5.text())
        DispatchQuantity=float(self.lineEdit_6.text())
        DispatchQuantity_1=str(DispatchQuantity)
        RejectionQuantity=float(self.lineEdit_7.text())
        RejectionQuantity_1=str(RejectionQuantity)
        ReasonOfRejection=str(self.lineEdit_8.text())
        CorrectiveAction=str(self.lineEdit_9.text())
        RootCause=str(self.lineEdit_10.text())
        PreventiveAction=str(self.lineEdit_11.text())
        Status=str(self.lineEdit_12.text())

        PPMValue=(RejectionQuantity/DispatchQuantity)*1000000

        if SrNo > 0 and \
           len(Date) > 0 and \
           len(CustomerNo) > 0 and \
           len(PartName) > 0 and \
           len(PartNo) > 0 and \
           len(DispatchQuantity_1) > 0 and \
           len(RejectionQuantity_1) > 0 and \
           len(ReasonOfRejection) > 0 and \
           len(CorrectiveAction) > 0 and \
           len(RootCause) > 0 and \
           len(PreventiveAction) > 0 and \
           len(Status) > 0 :
            print("")
            PPM=self.lineEdit_13.setText(str(PPMValue))
            self.ShowEntCustMessageBox("Customer Non-Conformance","see your PPM !")
        else:
            self.ShowEntCustWMessageBox("Customer Non-Conformance","Please Enter All Details")

    def CustNonConfCalSubmit(self,PPM):

        SrNo=int(self.lineEdit.text())
        Date=str(self.lineEdit_2.text())
        CustomerNo=str(self.lineEdit_3.text())
        PartName=str(self.lineEdit_4.text())
        PartNo=str(self.lineEdit_5.text())
        DispatchQuantity=float(self.lineEdit_6.text())
        #DispatchQuantity_1=str(DispatchQuantity)
        RejectionQuantity=float(self.lineEdit_7.text())
        #RejectionQuantity_1=str(RejectionQuantity)
        ReasonOfRejection=str(self.lineEdit_8.text())
        CorrectiveAction=str(self.lineEdit_9.text())
        RootCause=str(self.lineEdit_10.text())
        PreventiveAction=str(self.lineEdit_11.text())
        Status=str(self.lineEdit_12.text())

        PPMValue=str((RejectionQuantity/DispatchQuantity)*1000000)

        if SrNo > 0 and \
           len(Date) > 0 and \
           len(CustomerNo) > 0 and \
           len(PartName) > 0 and \
           len(PartNo) > 0 and \
           DispatchQuantity > 0 and \
           RejectionQuantity > 0 and \
           len(ReasonOfRejection) > 0 and \
           len(CorrectiveAction) > 0 and \
           len(RootCause) > 0 and \
           len(PreventiveAction) > 0 and \
           len(Status) > 0 and \
           len(PPMValue) > 0:
            print ("")

            connection=sqlite3.connect("PYDB.db")
            c=connection.cursor()

            c.execute("CREATE TABLE IF NOT EXISTS CustNonConfTable(SR_NO INTEGER, DATE TEXT, CUSTOMER_NO TEXT, PART_NAME TEXT, PART_NO TEXT, DISPLAY_QUALITY REAL, REJECTION_QUALITY REAL, REASON_OF_REJECTION TEXT, CORRECTIVE_ACTION TEXT, ROOT_CAUSE TEXT, PREVENTIVE_ACTION TEXT, STATUS TEXT, PPMVALUE REAL)")
            c.execute("INSERT INTO CustNonConfTable VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",(SrNo,Date,CustomerNo,PartName,PartNo,DispatchQuantity,RejectionQuantity,ReasonOfRejection,CorrectiveAction,RootCause,PreventiveAction,Status,PPMValue))

            connection.commit()
            c.close()
            connection.close()
            PPM1=str(self.lineEdit_13.setText(PPMValue))
            
            self.ShowEntCustMessageBox("Customer Non-Conformance","Details are added successfully !")
        else:
            
            self.ShowEntCustWMessageBox("Customer Non-Conformance","Please Enter All Details !")

    def onClickCNCSubmit(self):
        try:
            self.CustNonConfCalSubmit()
        except:
            self.ShowEntCustWMessageBox("Customer Non-Conformance","Please Enter All Details!")

    def onClickCNC(self):
        try:
            self.CustNonConfCal()
        except:
            self.ShowEntCustWMessageBox("Customer Non-Conformance","Please Enter All Details !")

    def setupUi(self, CustNonConf):

        CustNonConf.setObjectName("CustNonConf")
        CustNonConf.resize(1893, 185)
        CustNonConf.setMinimumSize(QtCore.QSize(1893, 185))
        CustNonConf.setMaximumSize(QtCore.QSize(1893, 185))
        self.centralwidget = QtWidgets.QWidget(CustNonConf)
        self.centralwidget.setObjectName("centralwidget")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(576, 10, 16, 121))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(141, 10, 14, 121))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(1481, 10, 16, 121))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1033, 10, 16, 121))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1197, 10, 16, 121))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(425, 10, 16, 121))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1765, 7, 20, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1629, 10, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(283, 10, 16, 121))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(876, 9, 16, 121))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(726, 9, 16, 121))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(1351, 9, 20, 121))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(0, 9, 16, 121))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(10, 3, 1871, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(10, 120, 1871, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 61, 31))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/logo2.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CustNonConf.setWindowIcon(icon)

        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(201, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(471, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(627, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(743, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(893, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1051, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1214, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1386, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1495, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1679, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1809, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(10, 40, 1871, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(1874, 8, 20, 121))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1760, 140, 112, 29))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.CustNonConfCalSubmit)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1630, 140, 112, 29))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.onClickCNC)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(15, 72, 121, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(158, 72, 121, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(302, 72, 121, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(444, 72, 131, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(594, 72, 131, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(743, 72, 131, 30))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(893, 72, 131, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(1054, 72, 131, 30))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(1216, 72, 131, 30))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(1369, 72, 111, 30))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(1498, 72, 131, 30))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(1646, 72, 120, 30))
        self.lineEdit_12.setObjectName("lineEdit_12")

        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(1784, 66, 91, 41))
        self.lineEdit_13.setObjectName("lineEdit_13")
        CustNonConf.setCentralWidget(self.centralwidget)

        self.retranslateUi(CustNonConf)
        QtCore.QMetaObject.connectSlotsByName(CustNonConf)

    def retranslateUi(self, CustNonConf):
        _translate = QtCore.QCoreApplication.translate
        CustNonConf.setWindowTitle(_translate("CustNonConf", "Customer Non-Conformance"))
        self.label.setText(_translate("CustNonConf", "Sr No."))
        self.label_2.setText(_translate("CustNonConf", "Date"))
        self.label_3.setText(_translate("CustNonConf", "Customer No."))
        self.label_4.setText(_translate("CustNonConf", "Part Name"))
        self.label_5.setText(_translate("CustNonConf", "Part No."))
        self.label_6.setText(_translate("CustNonConf", "Dispatch Quantity"))
        self.label_7.setText(_translate("CustNonConf", "Rejection Quantity"))
        self.label_8.setText(_translate("CustNonConf", "Reason of Rejection"))
        self.label_9.setText(_translate("CustNonConf", "Correctitive action"))
        self.label_10.setText(_translate("CustNonConf", "Root Cause"))
        self.label_11.setText(_translate("CustNonConf", "Preventive Action"))
        self.label_12.setText(_translate("CustNonConf", "Status"))
        self.label_13.setText(_translate("CustNonConf", "PPM"))
        self.pushButton.setText(_translate("CustNonConf", "SUBMIT"))
        self.pushButton_2.setText(_translate("CustNonConf","CALCULATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustNonConf = QtWidgets.QMainWindow()
    ui = Ui_CustNonConf()
    ui.setupUi(CustNonConf)
    CustNonConf.show()
    sys.exit(app.exec_())

