
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnterCusto(object):

    global ProductName

    def ShowEntCustMessageBox(self,title,message):  
        msgBox=QtWidgets.QMessageBox()
        msgBox.setWindowTitle(title)
        msgBox.setIcon(QtWidgets.QMessageBox.Information)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def ShowEntCustWMessageBox(self,title,message):
        msgBox=QtWidgets.QMessageBox()
        msgBox.setWindowTitle(title)
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def companyDetails(self):

        global ProductName,BuyersCode

        BuyersCode=str(self.lineEdit.text())
        CompanyName=str(self.lineEdit_2.text())
        Address=str(self.lineEdit_3.text())
        CurrLiveComp=str(self.lineEdit_4.text())
        Department=str(self.lineEdit_5.text())
        
        ProductName=str(self.lineEdit_9.text())
        ProductNo=str(self.lineEdit_10.text())
        MaterialGrade=str(self.lineEdit_11.text())
        MaterialSize=str(self.lineEdit_12.text())
        Price=str(self.lineEdit_13.text())
        CycleTime=str(self.lineEdit_14.text())

        connection=sqlite3.connect("PYDB.db")
        c=connection.cursor()
        c.execute("CREATE TABLE IF NOT EXISTS CompanyDetTable(BUYERS_CODE TEXT PRIMARY KEY NOT NULL, COMPANY_NAME TEXT, ADDRESS TEXT, CURRENT_LIVE_COMPLAINTS INTEGER, DEPARTMENT TEXT, PRODUCT_NAME TEXT, PRODUCT_NO INTEGER, MATERIAL_GRADE TEXT, MATERIAL_SIZE INTEGER, PRICE REAL, CYCLE_TIME REAL, FOREIGN KEY (PRODUCT_NAME) REFERENCES ProductDetailsTable_1(PRODUCT_NAME)); ")
        c.execute("INSERT INTO CompanyDetTable VALUES(?,?,?,?,?,?,?,?,?,?,?)",(BuyersCode,CompanyName,Address,CurrLiveComp,Department,ProductName,ProductNo,MaterialGrade,MaterialSize,Price,CycleTime))
        connection.commit()

        result=connection.execute("SELECT * FROM CompanyDetTable WHERE BUYERS_CODE = ?",(BuyersCode,))

        if (len(result.fetchone()) > 0):
            self.ShowEntCustMessageBox("Customer Details","Details are added successfully !")

        c.close()
        connection.close()

    def onClickClearTab1(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.lineEdit_8.clear()
        self.lineEdit_9.clear()
        self.lineEdit_10.clear()
        self.lineEdit_11.clear()
        self.lineEdit_12.clear()
        self.lineEdit_13.clear()
        self.lineEdit_14.clear()

    def onClickClearTab2(self):
        self.lineEdit_15.clear()
        self.lineEdit_16.clear()
        self.lineEdit_17.clear()
        self.lineEdit_18.clear()
        self.lineEdit_19.clear()
        self.lineEdit_20.clear()
        self.lineEdit_21.clear()
        self.lineEdit_22.clear()
        self.lineEdit_23.clear()
        self.lineEdit_24.clear()
        self.lineEdit_25.clear()

    def deptDetails(self):

        BuyersCode=str(self.lineEdit.text())

        Department=str(self.lineEdit_5.text())
        Name=str(self.lineEdit_6.text())
        Designation=str(self.lineEdit_7.text())
        ContactNo=str(self.lineEdit_8.text())

        connection=sqlite3.connect("PYDB.db")
        c=connection.cursor()
        c.execute("CREATE TABLE IF NOT EXISTS DeptDetTable(BUYERS_CODE1 TEXT,DEPARTMENT TEXT, NAME TEXT, DESIGNATION TEXT, CONTACT_NO INTEGER, FOREIGN KEY (DEPARTMENT) REFERENCES DeptDetTable(DEPARTMENT))") 
        c.execute("INSERT INTO DeptDetTable VALUES(?,?,?,?,?)",(BuyersCode,Department,Name,Designation,ContactNo))
        connection.commit()

        c.close()
        connection.close()

    def productDetails_1(self,ProductName):

        ProductName=str(self.lineEdit_9.text())
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        ProductDrawing, _ =QtWidgets.QFileDialog.getOpenFileName(None,'Open file',"","Image files (*.jpeg *.jpg);;All Files(*.*)",  options=options)
        file=open(ProductName + ".jpeg","rb")
        
        connection=sqlite3.connect("PYDB.db")
        c=connection.cursor()
         
        c.execute("CREATE TABLE IF NOT EXISTS ProductDetailsTable_1(PRODUCT_NAME TEXT PRIMARY KEY, IMAGES BLOB)")
        c.execute("INSERT INTO ProductDetailsTable_1 VALUES(?,?)", (ProductName,sqlite3.Binary(file.read())) )
        connection.commit()

        file.close()
        c.close()
        connection.close()

        self.ShowEntCustMessageBox("Customer Details","File is uploaded successfully !")

    def onClickEntCust(self,ProductName):
        try:
            self.companyDetails()
            self.deptDetails()
        except sqlite3.IntegrityError:
            self.ShowEntCustWMessageBox("Customer Details","Details Exists !")
        except Exception:
            self.ShowEntCustWMessageBox("Customer Details","There is Error in Adding Details !") 

    def onClickFileUpload(self,ProductName):
        try:
            self.productDetails_1(ProductName)
        except FileNotFoundError:
            self.ShowEntCustWMessageBox("Customer Details","Drawing Upload - Please Enter Valid Product Name!")
        except sqlite3.IntegrityError:
            self.ShowEntCustWMessageBox("Customer Details","File Exists !")
        except Exception:
            self.ShowEntCustWMessageBox("Customer Details","Drawing Upload - There is Error in Uploading file !")

    def productDetails_1Update(self,ProductName):

        ProductName=str(self.lineEdit_20.text())
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        ProductDrawing, _ =QtWidgets.QFileDialog.getOpenFileName(None,'Open file',"","Image files (*.jpeg *.jpg);;All Files(*.*)",  options=options)
        file=open(ProductName + ".jpeg","rb")
        
        connection=sqlite3.connect("PYDB.db")
        c=connection.cursor()
         
        c.execute("DELETE FROM ProductDetailsTable_1 WHERE PRODUCT_NAME=?",(ProductName,))
        c.execute("INSERT INTO ProductDetailsTable_1 VALUES(?,?)", (ProductName,sqlite3.Binary(file.read())))
        connection.commit()

        file.close()
        c.close()
        connection.close()

        self.ShowEntCustMessageBox("Customer Details","File is uploaded successfully !")

    def onClickFileUpload1(self,ProductName):
        try:
            self.productDetails_1Update(ProductName)
        except FileNotFoundError:
            self.ShowEntCustWMessageBox("Customer Details","Drawing Upload - Please Enter Valid Product Name!")
        except sqlite3.IntegrityError:
            self.ShowEntCustWMessageBox("Customer Details","File Exists !")
        except Exception:
            self.ShowEntCustWMessageBox("Customer Details","Drawing Upload - There is Error in Uploading file !")

    def deptDetailsUpdate(self):
        
        BuyersCode=str(self.lineEdit_15.text())

        Department=str(self.lineEdit_16.text())
        Name=str(self.lineEdit_17.text())
        Designation=str(self.lineEdit_18.text())
        ContactNo=str(self.lineEdit_19.text())

        connection=sqlite3.connect("PYDB.db")
        c=connection.cursor()
        c.execute("INSERT INTO DeptDetTable VALUES(?,?,?,?,?)",(BuyersCode,Department,Name,Designation,ContactNo))
        connection.commit()

        c.close()
        connection.close()

        self.ShowEntCustMessageBox("Customer Details","Details are Added successfully !")

    def onClickDDBUpdate(self):
        try:
            self.deptDetailsUpdate()
        except sqlite3.IntegrityError:
            self.ShowEntCustWMessageBox("Customer Details","Details Exists !")
        except Exception:
            self.ShowEntCustWMessageBox("Customer Details","There is Error in Adding Details !")

    def companyDetailsUpdate(self):

        BuyersCode=str(self.lineEdit_15.text())

        ProductName=str(self.lineEdit_20.text())
        ProductNo=str(self.lineEdit_21.text())
        MaterialGrade=str(self.lineEdit_22.text())
        MaterialSize=str(self.lineEdit_23.text())
        Price=str(self.lineEdit_24.text())
        CycleTime=str(self.lineEdit_25.text())

        connection=sqlite3.connect("PYDB.db")
        c=connection.cursor()
        c.execute("UPDATE CompanyDetTable SET PRODUCT_NAME=?,PRODUCT_NO=?,MATERIAL_GRADE=?,MATERIAL_SIZE=?,PRICE=?,CYCLE_TIME=? WHERE BUYERS_CODE = ?",(ProductName,ProductNo,MaterialGrade,MaterialSize,Price,CycleTime,BuyersCode))
        connection.commit()

        c.close()
        connection.close()

        self.ShowEntCustMessageBox("Customer Details","Details are Updated successfully !")

    def onClickCDBUpdate(self):
        try:
            self.companyDetailsUpdate()
        except sqlite3.IntegrityError:
            self.ShowEntCustWMessageBox("Customer Details","Details Exists !")
        except Exception:
            self.ShowEntCustWMessageBox("Customer Details","There is Error in Adding Details !")

    def setupUi(self, EnterCusto):

        EnterCusto.setObjectName("EnterCusto")
        EnterCusto.resize(771, 784)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EnterCusto.sizePolicy().hasHeightForWidth())
        EnterCusto.setSizePolicy(sizePolicy)
        EnterCusto.setMinimumSize(QtCore.QSize(771, 784))
        EnterCusto.setMaximumSize(QtCore.QSize(771, 784))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/logo2.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EnterCusto.setWindowIcon(icon)

        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        EnterCusto.setFont(font)
        EnterCusto.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        EnterCusto.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(EnterCusto)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(14, 9, 741, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(360, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.onClickEntCust)

        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.onClickClearTab1)

        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(20, 490, 571, 181))
        self.line_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(30, 210, 671, 141))
        self.tableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableView.setAutoFillBackground(True)
        self.tableView.setObjectName("tableView")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(270, 210, 101, 51))
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_8.setObjectName("label_8")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(600, 490, 121, 91))
        self.label_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_17.setObjectName("label_17")
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(20, 490, 691, 181))
        self.line_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.tableView_2 = QtWidgets.QTableView(self.tab)
        self.tableView_2.setGeometry(QtCore.QRect(20, 490, 691, 181))
        self.tableView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableView_2.setObjectName("tableView_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(80, 210, 111, 51))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_7.setObjectName("label_7")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(303, 490, 291, 181))
        self.line_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(480, 490, 101, 91))
        self.label_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_16.setObjectName("label_16")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(22, 490, 281, 181))
        self.line_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(30, 440, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 350, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(40, 490, 111, 91))
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(340, 490, 111, 91))
        self.label_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_14.setObjectName("label_14")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(32, 210, 331, 141))
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(370, 210, 331, 141))
        self.line_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(190, 490, 111, 91))
        self.label_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_15.setObjectName("label_15")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(580, 210, 101, 51))
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_10.setObjectName("label_10")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(30, 250, 671, 21))
        self.line_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(420, 210, 111, 51))
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 400, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setObjectName("label_2")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(460, 490, 251, 181))
        self.line_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(50, 600, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton.setFont(font)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton.setObjectName("toolButton")
        self.toolButton.clicked.connect(self.productDetails_1)

        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.line_10 = QtWidgets.QFrame(self.tab)
        self.line_10.setGeometry(QtCore.QRect(20, 489, 691, 181))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(20, 490, 571, 181))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(590, 495, 121, 81))
        self.label_18.setObjectName("label_18")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(32, 210, 671, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(220, 11, 501, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 50, 501, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 90, 501, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 130, 501, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 281, 113, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 281, 113, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(400, 281, 113, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(560, 281, 113, 41))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 401, 521, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(180, 441, 521, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_11.setGeometry(QtCore.QRect(180, 601, 113, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(320, 601, 113, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_13.setGeometry(QtCore.QRect(460, 601, 113, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_14.setGeometry(QtCore.QRect(590, 601, 113, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")

        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.line_5.raise_()
        self.tableView.raise_()
        self.label_8.raise_()
        self.label_17.raise_()
        self.line_9.raise_()
        self.tableView_2.raise_()
        self.label_7.raise_()
        self.line_8.raise_()
        self.label_16.raise_()
        self.line_6.raise_()
        self.label_12.raise_()
        self.label_5.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.line_2.raise_()
        self.label_15.raise_()
        self.label_4.raise_()
        self.label_10.raise_()
        self.line_4.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.line_7.raise_()
        self.label_3.raise_()
        self.line_10.raise_()
        self.label_18.raise_()
        self.line_3.raise_()
        self.line.raise_()
        self.line_11.raise_()
        self.toolButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.toolButton_2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_2.setGeometry(QtCore.QRect(40, 500, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_2.setObjectName("toolButton_2")

        self.tableView_3 = QtWidgets.QTableView(self.tab_2)
        self.tableView_3.setGeometry(QtCore.QRect(20, 110, 671, 141))
        self.tableView_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableView_3.setAutoFillBackground(True)
        self.tableView_3.setObjectName("tableView_3")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(590, 390, 121, 91))
        self.label_19.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(180, 390, 111, 91))
        self.label_20.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 70, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(70, 110, 111, 51))
        self.label_22.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_22.setObjectName("label_22")
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setGeometry(QtCore.QRect(20, 150, 671, 21))
        self.line_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(10, 390, 691, 181))
        self.line_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(10, 250, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_23.setObjectName("label_23")
        self.line_14 = QtWidgets.QFrame(self.tab_2)
        self.line_14.setGeometry(QtCore.QRect(22, 110, 331, 141))
        self.line_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(20, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_24.setObjectName("label_24")
        self.line_15 = QtWidgets.QFrame(self.tab_2)
        self.line_15.setGeometry(QtCore.QRect(293, 390, 291, 181))
        self.line_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.tab_2)
        self.line_16.setGeometry(QtCore.QRect(450, 390, 251, 181))
        self.line_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")

        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 600, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.onClickCDBUpdate)

        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 600, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.deptDetailsUpdate)

        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 600, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.onClickClearTab2)

        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(330, 390, 111, 91))
        self.label_25.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(410, 110, 111, 51))
        self.label_26.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(470, 390, 101, 91))
        self.label_27.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_27.setObjectName("label_27")
        self.line_17 = QtWidgets.QFrame(self.tab_2)
        self.line_17.setGeometry(QtCore.QRect(10, 390, 571, 181))
        self.line_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(20, 300, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_29.setObjectName("label_29")
        self.tableView_4 = QtWidgets.QTableView(self.tab_2)
        self.tableView_4.setGeometry(QtCore.QRect(10, 390, 691, 181))
        self.tableView_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableView_4.setObjectName("tableView_4")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(260, 110, 101, 51))
        self.label_30.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_30.setObjectName("label_30")
        self.line_18 = QtWidgets.QFrame(self.tab_2)
        self.line_18.setGeometry(QtCore.QRect(22, 110, 671, 141))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.tab_2)
        self.line_19.setGeometry(QtCore.QRect(360, 110, 331, 141))
        self.line_19.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.tab_2)
        self.line_20.setGeometry(QtCore.QRect(10, 390, 571, 181))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.tab_2)
        self.line_21.setGeometry(QtCore.QRect(12, 390, 281, 181))
        self.line_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.tab_2)
        self.line_22.setGeometry(QtCore.QRect(10, 389, 691, 181))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(570, 110, 101, 51))
        self.label_31.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(30, 390, 111, 91))
        self.label_32.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_32.setObjectName("label_32")
        self.line_23 = QtWidgets.QFrame(self.tab_2)
        self.line_23.setGeometry(QtCore.QRect(170, 390, 531, 181))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.tab_2)
        self.line_24.setGeometry(QtCore.QRect(440, 390, 261, 181))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(170, 390, 111, 91))
        self.label_33.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(580, 390, 121, 91))
        self.label_34.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(460, 390, 101, 91))
        self.label_35.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(320, 390, 111, 91))
        self.label_36.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_36.setObjectName("label_36")

        self.toolButton_3 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_3.setGeometry(QtCore.QRect(40, 500, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_3.clicked.connect(self.productDetails_1Update)

        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(160, 20, 561, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(50, 180, 113, 41))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(220, 180, 113, 41))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(390, 180, 113, 41))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(550, 180, 113, 41))
        self.lineEdit_19.setObjectName("lineEdit_19")

        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(160, 301, 541, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")

        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(160, 341, 541, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(170, 500, 113, 41))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(310, 500, 113, 41))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(450, 500, 113, 41))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(580, 500, 113, 41))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.toolButton_2.raise_()
        self.tableView_3.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.label_23.raise_()
        self.line_14.raise_()
        self.label_24.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.line_17.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.tableView_4.raise_()
        self.label_30.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.line_21.raise_()
        self.line_22.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.line_23.raise_()
        self.line_24.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.toolButton_3.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_19.raise_()
        self.lineEdit_20.raise_()
        self.lineEdit_21.raise_()
        self.lineEdit_22.raise_()
        self.lineEdit_23.raise_()
        self.lineEdit_24.raise_()
        self.lineEdit_25.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        EnterCusto.setCentralWidget(self.centralwidget)

        self.retranslateUi(EnterCusto)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EnterCusto)

    def retranslateUi(self, EnterCusto):
        _translate = QtCore.QCoreApplication.translate
        EnterCusto.setWindowTitle(_translate("EnterCusto", "Enter Customer Details"))
        self.pushButton.setText(_translate("EnterCusto", "SUBMIT"))
        self.pushButton_2.setText(_translate("EnterCusto", "CLEAR"))
        self.label_8.setText(_translate("EnterCusto", "Name"))
        self.label_17.setText(_translate("EnterCusto", "Cycle Time (sec)"))
        self.label_7.setText(_translate("EnterCusto", "Department"))
        self.label_16.setText(_translate("EnterCusto", "Price (INR.)"))
        self.label_12.setText(_translate("EnterCusto", "Product No."))
        self.label_5.setText(_translate("EnterCusto", "Product Details"))
        self.label_13.setText(_translate("EnterCusto", "Product Drawing"))
        self.label_14.setText(_translate("EnterCusto", "Material Size"))
        self.label_15.setText(_translate("EnterCusto", "Material Grade"))
        self.label_4.setText(_translate("EnterCusto", "Current Live Complaints :"))
        self.label_10.setText(_translate("EnterCusto", "Contact No."))
        self.label_9.setText(_translate("EnterCusto", "Designation"))
        self.label_11.setText(_translate("EnterCusto", "Product Name"))
        self.label.setText(_translate("EnterCusto", "Buyer\'s Code :"))
        self.label_6.setText(_translate("EnterCusto", "List Of Department Persons"))
        self.label_2.setText(_translate("EnterCusto", "Company Name :"))
        self.toolButton.setText(_translate("EnterCusto", "UPLOAD"))
        self.label_3.setText(_translate("EnterCusto", "Address :"))
        self.label_18.setText(_translate("EnterCusto", "Cycle Time (Sec)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("EnterCusto", "Enter Customer Details"))
        self.toolButton_2.setText(_translate("EnterCusto", "UPLOAD"))
        self.label_19.setText(_translate("EnterCusto", "Cycle Time (sec)"))
        self.label_20.setText(_translate("EnterCusto", "Material Grade"))
        self.label_21.setText(_translate("EnterCusto", "List Of Department Persons"))
        self.label_22.setText(_translate("EnterCusto", "Department"))
        self.label_23.setText(_translate("EnterCusto", "Product Details"))
        self.label_24.setText(_translate("EnterCusto", "Product No."))
        self.pushButton_3.setText(_translate("EnterCusto", "UPDATE"))
        self.pushButton_4.setText(_translate("EnterCusto", "ADD Department Details"))
        self.pushButton_5.setText(_translate("EnterCusto", "CLEAR"))
        self.label_25.setText(_translate("EnterCusto", "Material Size"))
        self.label_26.setText(_translate("EnterCusto", "Designation"))
        self.label_27.setText(_translate("EnterCusto", "Price (INR.)"))
        self.label_28.setText(_translate("EnterCusto", "Product Name"))
        self.label_29.setText(_translate("EnterCusto", "Buyer\'s Code :"))
        self.label_30.setText(_translate("EnterCusto", "Name"))
        self.label_31.setText(_translate("EnterCusto", "Contact No."))
        self.label_32.setText(_translate("EnterCusto", "Product Drawing"))
        self.label_33.setText(_translate("EnterCusto", "Material Grade"))
        self.label_34.setText(_translate("EnterCusto", "Cycle Time (sec)"))
        self.label_35.setText(_translate("EnterCusto", "Price (INR.)"))
        self.label_36.setText(_translate("EnterCusto", "Material Size"))
        self.toolButton_3.setText(_translate("EnterCusto", "UPLOAD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("EnterCusto", "Edit Customer Details"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnterCusto = QtWidgets.QMainWindow()
    ui = Ui_EnterCusto()
    ui.setupUi(EnterCusto)
    EnterCusto.show()
    sys.exit(app.exec_())

