# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMSq.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 2000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(674, 132))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 26))
        self.menubar.setObjectName("menubar")
        self.menuCustomer_Details = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.menuCustomer_Details.setFont(font)
        self.menuCustomer_Details.setObjectName("menuCustomer_Details")
        self.menuQMS = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.menuQMS.setFont(font)
        self.menuQMS.setObjectName("menuQMS")
        self.menuNon_Conformance = QtWidgets.QMenu(self.menuQMS)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.menuNon_Conformance.setFont(font)
        self.menuNon_Conformance.setObjectName("menuNon_Conformance")
        self.menuPart_Production_Calculator = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.menuPart_Production_Calculator.setFont(font)
        self.menuPart_Production_Calculator.setObjectName("menuPart_Production_Calculator")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuReiceive_Material = QtWidgets.QMenu(self.menubar)
        self.menuReiceive_Material.setObjectName("menuReiceive_Material")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEnter_Customer_Details = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.actionEnter_Customer_Details.setFont(font)
        self.actionEnter_Customer_Details.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionEnter_Customer_Details.setObjectName("actionEnter_Customer_Details")
        self.actionSearch_Customer_Details = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.actionSearch_Customer_Details.setFont(font)
        self.actionSearch_Customer_Details.setObjectName("actionSearch_Customer_Details")
        self.actionPDIR = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.actionPDIR.setFont(font)
        self.actionPDIR.setObjectName("actionPDIR")
        self.actionAubiuf = QtWidgets.QAction(MainWindow)
        self.actionAubiuf.setObjectName("actionAubiuf")
        self.actionMRM = QtWidgets.QAction(MainWindow)
        self.actionMRM.setObjectName("actionMRM")
        self.actionCustomer = QtWidgets.QAction(MainWindow)
        self.actionCustomer.setObjectName("actionCustomer")
        self.actionInhouse = QtWidgets.QAction(MainWindow)
        self.actionInhouse.setObjectName("actionInhouse")
        self.actionEdit_Customer_Details = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.actionEdit_Customer_Details.setFont(font)
        self.actionEdit_Customer_Details.setObjectName("actionEdit_Customer_Details")
        self.actionInput_Caliberation = QtWidgets.QAction(MainWindow)
        self.actionInput_Caliberation.setObjectName("actionInput_Caliberation")
        self.actionShow_Caliberation = QtWidgets.QAction(MainWindow)
        self.actionShow_Caliberation.setObjectName("actionShow_Caliberation")
        self.actionEdit_Caliberation = QtWidgets.QAction(MainWindow)
        self.actionEdit_Caliberation.setObjectName("actionEdit_Caliberation")
        self.actionInput_Machine_Capability = QtWidgets.QAction(MainWindow)
        self.actionInput_Machine_Capability.setObjectName("actionInput_Machine_Capability")
        self.actionEdit_Machine_Capabilty = QtWidgets.QAction(MainWindow)
        self.actionEdit_Machine_Capabilty.setObjectName("actionEdit_Machine_Capabilty")
        self.actionShow_Machine_Capabilty = QtWidgets.QAction(MainWindow)
        self.actionShow_Machine_Capabilty.setObjectName("actionShow_Machine_Capabilty")
        self.actionInput_SPC = QtWidgets.QAction(MainWindow)
        self.actionInput_SPC.setObjectName("actionInput_SPC")
        self.actionEdit_SPC = QtWidgets.QAction(MainWindow)
        self.actionEdit_SPC.setObjectName("actionEdit_SPC")
        self.actionShow_SPC = QtWidgets.QAction(MainWindow)
        self.actionShow_SPC.setObjectName("actionShow_SPC")
        self.actionInput_MSA = QtWidgets.QAction(MainWindow)
        self.actionInput_MSA.setObjectName("actionInput_MSA")
        self.actionEdit_MSA = QtWidgets.QAction(MainWindow)
        self.actionEdit_MSA.setObjectName("actionEdit_MSA")
        self.actionShow_MSA = QtWidgets.QAction(MainWindow)
        self.actionShow_MSA.setObjectName("actionShow_MSA")
        self.actionInput_Vender_Audits = QtWidgets.QAction(MainWindow)
        self.actionInput_Vender_Audits.setObjectName("actionInput_Vender_Audits")
        self.actionEdit_Vender_Audits = QtWidgets.QAction(MainWindow)
        self.actionEdit_Vender_Audits.setObjectName("actionEdit_Vender_Audits")
        self.actionShow_Vender_Audits = QtWidgets.QAction(MainWindow)
        self.actionShow_Vender_Audits.setObjectName("actionShow_Vender_Audits")
        self.actionInput_Internal_ISO_Audits = QtWidgets.QAction(MainWindow)
        self.actionInput_Internal_ISO_Audits.setObjectName("actionInput_Internal_ISO_Audits")
        self.actionEdit_Internal_ISO_Audits = QtWidgets.QAction(MainWindow)
        self.actionEdit_Internal_ISO_Audits.setObjectName("actionEdit_Internal_ISO_Audits")
        self.actionCaliberation = QtWidgets.QAction(MainWindow)
        self.actionCaliberation.setObjectName("actionCaliberation")
        self.actionMachine_Capability = QtWidgets.QAction(MainWindow)
        self.actionMachine_Capability.setObjectName("actionMachine_Capability")
        self.actionSPC = QtWidgets.QAction(MainWindow)
        self.actionSPC.setObjectName("actionSPC")
        self.actionMSA = QtWidgets.QAction(MainWindow)
        self.actionMSA.setObjectName("actionMSA")
        self.actionVender_Audits = QtWidgets.QAction(MainWindow)
        self.actionVender_Audits.setObjectName("actionVender_Audits")
        self.actionPPC = QtWidgets.QAction(MainWindow)
        self.actionPPC.setObjectName("actionPPC")
        self.menuCustomer_Details.addAction(self.actionEnter_Customer_Details)
        self.menuCustomer_Details.addAction(self.actionSearch_Customer_Details)
        self.menuNon_Conformance.addAction(self.actionCustomer)
        self.menuNon_Conformance.addAction(self.actionInhouse)
        self.menuQMS.addAction(self.actionPDIR)
        self.menuQMS.addAction(self.menuNon_Conformance.menuAction())
        self.menuPart_Production_Calculator.addAction(self.actionPPC)
        self.menuReiceive_Material.addAction(self.actionCaliberation)
        self.menuReiceive_Material.addAction(self.actionMachine_Capability)
        self.menuReiceive_Material.addAction(self.actionSPC)
        self.menuReiceive_Material.addAction(self.actionMSA)
        self.menuReiceive_Material.addAction(self.actionVender_Audits)
        self.menubar.addAction(self.menuCustomer_Details.menuAction())
        self.menubar.addAction(self.menuQMS.menuAction())
        self.menubar.addAction(self.menuPart_Production_Calculator.menuAction())
        self.menubar.addAction(self.menuReiceive_Material.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuCustomer_Details.setTitle(_translate("MainWindow", "Customer Details   "))
        self.menuQMS.setTitle(_translate("MainWindow", "QMS   "))
        self.menuNon_Conformance.setTitle(_translate("MainWindow", "Non-Conformance"))
        self.menuPart_Production_Calculator.setTitle(_translate("MainWindow", "Part Production Calculator   "))
        self.menuAbout.setTitle(_translate("MainWindow", "About   "))
        self.menuReiceive_Material.setTitle(_translate("MainWindow", "Plans   "))
        self.actionEnter_Customer_Details.setText(_translate("MainWindow", "Enter and Edit Customer Details"))
        self.actionSearch_Customer_Details.setText(_translate("MainWindow", "Search Customer Details"))
        self.actionPDIR.setText(_translate("MainWindow", "PDIR"))
        self.actionAubiuf.setText(_translate("MainWindow", "aubiuf"))
        self.actionMRM.setText(_translate("MainWindow", "MRM"))
        self.actionCustomer.setText(_translate("MainWindow", "Customer"))
        self.actionInhouse.setText(_translate("MainWindow", "Inhouse"))
        self.actionEdit_Customer_Details.setText(_translate("MainWindow", "Edit Customer Details"))
        self.actionInput_Caliberation.setText(_translate("MainWindow", "Input Caliberation"))
        self.actionShow_Caliberation.setText(_translate("MainWindow", "Show Caliberation"))
        self.actionEdit_Caliberation.setText(_translate("MainWindow", "Edit Caliberation"))
        self.actionInput_Machine_Capability.setText(_translate("MainWindow", "Input Machine Capability"))
        self.actionEdit_Machine_Capabilty.setText(_translate("MainWindow", "Edit Machine Capabilty"))
        self.actionShow_Machine_Capabilty.setText(_translate("MainWindow", "Show Machine Capabilty"))
        self.actionInput_SPC.setText(_translate("MainWindow", "Input SPC"))
        self.actionEdit_SPC.setText(_translate("MainWindow", "Edit SPC"))
        self.actionShow_SPC.setText(_translate("MainWindow", "Show SPC"))
        self.actionInput_MSA.setText(_translate("MainWindow", "Input MSA"))
        self.actionEdit_MSA.setText(_translate("MainWindow", "Edit MSA"))
        self.actionShow_MSA.setText(_translate("MainWindow", "Show MSA"))
        self.actionInput_Vender_Audits.setText(_translate("MainWindow", "Input Vender Audits"))
        self.actionEdit_Vender_Audits.setText(_translate("MainWindow", "Edit Vender Audits"))
        self.actionShow_Vender_Audits.setText(_translate("MainWindow", "Show Vender Audits"))
        self.actionInput_Internal_ISO_Audits.setText(_translate("MainWindow", "Input Internal ISO Audits"))
        self.actionEdit_Internal_ISO_Audits.setText(_translate("MainWindow", "Edit Internal ISO Audits "))
        self.actionCaliberation.setText(_translate("MainWindow", "Caliberation"))
        self.actionMachine_Capability.setText(_translate("MainWindow", "Machine Capability"))
        self.actionSPC.setText(_translate("MainWindow", "SPC"))
        self.actionMSA.setText(_translate("MainWindow", "MSA"))
        self.actionVender_Audits.setText(_translate("MainWindow", "Vender Audits"))
        self.actionPPC.setText(_translate("MainWindow", "PPC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

